# Generated by Django 3.0.1 on 2020-07-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200719_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
